apiVersion: entando.org/v1
kind: EntandoApp
metadata:
  namespace: entando
  name: quickstart
spec:
  environmentVariables:
  - name: SPRING_PROFILES_ACTIVE
    value: "default,swagger"
  dbms: postgresql
  ingressHostName: quickstart.$IP.nip.io
  standardServerImage: tomcat
  replicas: 1
