apiVersion: entando.org/v1
kind: EntandoApp
metadata:
  namespace: entando
  name: quickstart
spec:
  environmentVariables: []
  dbms: embedded
  ingressHostName: quickstart.$IP.nip.io
  standardServerImage: eap
  replicas: 1
